"""Changed Job Description Table

Revision ID: 2173e6e6d0b0
Revises: 5b464f7a5b87
Create Date: 2026-07-06 21:04:01.132969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2173e6e6d0b0'
down_revision: Union[str, Sequence[str], None] = '5b464f7a5b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('file_size', sa.Integer(), nullable=False))
    op.alter_column('job_descriptions', 'raw_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_descriptions', 'raw_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('job_descriptions', 'file_size')
    # ### end Alembic commands ###
